import React from "react";

const Page = () => {
  return (
    <div className="container mx-auto p-4 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 ">
      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">Monthly Revenue Report</h2>
        <p className="text-lg">
          This report provides insights into the monthly revenue generated by
          the parking system.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Vehicle Occupancy Report
        </h2>
        <p className="text-lg">
          The vehicle occupancy report shows the utilization of parking spaces
          over time.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Customer Behavior and Trends
        </h2>
        <p className="text-lg">
          Analysis of customer demographics, preferences, and trends in parking
          behavior.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Space Management Analysis
        </h2>
        <p className="text-lg">
          Distribution of parking spaces, turnover rates, and optimization
          recommendations.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Ticketing and Violations Analysis
        </h2>
        <p className="text-lg">
          Frequency and types of parking violations, revenue from fines, and
          enforcement trends.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Environmental Impact Assessment
        </h2>
        <p className="text-lg">
          Calculation of carbon emissions, environmental impact, and comparisons
          of eco-friendly alternatives.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Operational Efficiency Metrics
        </h2>
        <p className="text-lg">
          Analysis of operational costs, efficiency metrics, and areas for
          improvement.
        </p>
      </div>

      <div className="mb-8 bg-white/5 backdrop-blur-md rounded-xl border border-white/10 p-5">
        <h2 className="text-2xl font-semibold mb-2">
          Safety and Security Overview
        </h2>
        <p className="text-lg">
          Incidents, accidents, security measures, and their effectiveness.
        </p>
      </div>
    </div>
  );
};

export default Page;
